### ISSUE TITLE
Tardanza en carga de datos

### ISSUE THREAD

**Issue by VivianBass** [CONABIO/climasagrobiodiversidad#1]
Actualmente la query que se utiliza para la app es la siguiente, la cual llama todas las características cuantitativas y cualitativas además de las condiciones del sitio. Esto hace que la recuperación de datos sea súmamente tardada, además de que solamente se llaman 1000 registros cuando muchos taxones tienen muchos más.

```
{
  taxons(pagination:{limit:1} search:{field:taxon_id value:"79251ANGIO" operator:eq}){
    taxon_id
    taxon
    registroConnection(pagination:{first:1000}){
      edges{
        node{
          id
          sitio{
            latitud
            longitud
            altitud
            estado
            municipio
            localidad
            condiciones_sitioFilter(pagination:{limit:2}){
              sitio_id
              condicion
              valor
              unidad
              nombre_corto
              fuente
            }
          }
          caracteristicas_cualitativasFilter(pagination:{limit:10} search:{field:nombre_corto value:"color_grano" operator:eq }){
            nombre_corto
            valor
          }
          caracteristicas_cuantitativasFilter(pagination:{limit:10} search:{field:nombre_corto value:"hileras_mazorca" operator:eq }){
            nombre_corto
            valor
          }
          }
        }
      }
    }
  }
```

En el código podemos ver que el resultado se itera registro por registro, por lo que pensamos que hacer una query directamente a zacatuche -para no triangular peticiones- sería suficiente para llamar todos los datos que necesitamos de registro y sitio y posteriormente, en cada iteración realizar la petición de características y condiciones a nuestra api, o bien, ver si podemos conectarnos directamente a la base aunque se encuentre en otro servidor.

**Comment by AliciaMstt** [comment]
Acordamos que hay que revisar:


1. Si resuelve con un modelo central en vez de tener que brincar de un modelo a otro (estamos usando mal GraphQL?)
2. Si se resuelve haciendo some how queries más chiquitas (5-10 items por pagina) (estamos usando mal GraphQL?)

1 y 2 podrían ser una estancia / servicio social de gente de compu a quienes les guste optimizar

Solución Quick and as usual:
Bajar los datos completos y actualizar diariamente.

**Comment by VivianBass** [comment]
Implementando los índices a todas las llaves foráneas se redujeron los tiempos en gran medida. Uno de los taxones que tomaba más tiempo es el Olotillo, con estos cambios se redujo a 14 segundos.

**Comment by VivianBass** [comment]
Aunque los índices sí ayudaron a hacer más rápidas las querys, decidimos bajar los datos a csv planos en donde debería ser mucho más rápido el procesamiento.
